default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Quartet_development
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: password #<%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: db #<%= ENV.fetch("MYSQL_HOST", "db") %>

test:
  <<: *default
  database: Quartet_test

production:
  <<: *default
  database: Quartet_production
  username: <%= ENV["QUARTET_DATABASE_USERNAME"] %>
  password: <%= ENV["QUARTET_DATABASE_PASSWORD"] %>
